#! /usr/bin/env zsh

cd ~/Dropbox/programming/website/
bundle exec jekyll b
git add -A
git commit -m "post update"
cd _site
git add -A
git commit -m "post update"
git push origin master
echo post done!!
